name: Build Project

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"

      - name: Install Turborepo dependencies
        run: npm install

      - name: Build all packages
        run: npm run build -- --affected

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            .turbo
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Check types
        run: npm run check-types

      - name: Lint
        run: npm run lint
